name: CI

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci ## similar to npm install but more used in CI environments, link https://docs.npmjs.com/cli/v9/commands/npm-ci
      - run: npm run format:check ## check code format
      - run: npm test -- --coverage  ## we run test www
        env: 
          CI: true

